imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        connections:
            write:
                driver:   %db.write.driver%
                host:     %db.write.host%
                port:     %db.write.port%
                user:     %db.write.user%
                password: %db.write.password%
                path:     %db.write.path%
                charset:  UTF8
            read:
                driver:   %db.read.driver%
                host:     %db.read.host%
                port:     %db.read.port%
                user:     %db.read.user%
                password: %db.read.password%
                path:     %db.read.path%
                charset:  UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            write:
                connection: write
                auto_mapping: false
                mappings:
                    AcmeUserBundle:
                        type: xml
                        prefix: Acme\UserBundle\Domain\Model
                        dir: %kernel.root_dir%/../src/Acme/UserBundle/Resources/config/doctrine/model
            read:
                connection: read
                auto_mapping: false
                mappings:
                    AcmeUserBundle:
                        type: xml
                        prefix: Acme\UserBundle\Data
                        dir: %kernel.root_dir%/../src/Acme/UserBundle/Resources/config/doctrine/data

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

lite_cqrs:
    monolog: true
