user_register:
    pattern: /register
    defaults: { _controller: "acme_user.web.controller.registration:registerAction" }

user_list:
    pattern: /users
    defaults: { _controller: "acme_user.web.controller.view:listAction" }